export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CREATEWATE_BEGIN = "CREATEWASTE_BEGIN";
export const CREATEWASTE_SUCCESS = "CREATEWASTE_SUCCESS";
export const CREATEWASTE_ERROR = "CREATEWASTE_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const COLLECTWASTE_BEGIN = "COLLECTWASTE_BEGIN";
export const COLLECTWASTE_SUCCESS = "COLLECTWASTE_SUCCESS";
export const COLLECTWASTE_ERROR = "COLLECTWASTE_ERROR";

export const ALL_WASTE_BEGIN = "ALL_WASTE_BEGIN";
export const ALL_WASTE_SUCCESS = "ALL_WASTE_SUCCESS";
export const ALL_WASTE_ERROR = "ALL_WASTE_ERROR";

export const SHOWSTATS_BEGIN = "SHOWSTATS_BEGIN";
export const SHOWSTATS_SUCCESS = "SHOWSTATS_SUCCESS";
export const SHOWSTATS_ERROR = "SHOWSTATS_ERROR";

export const UPDATEUSER_BEGIN = "UPDATEUSER_BEGIN";
export const UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATEUSER_ERROR = "UPDATEUSER_ERROR";

export const DELETEWASTE_BEGIN = "DELETEWASTE_BEGIN";
export const DELETEWASTE_SUCCESS = "DELETEWASTE_SUCCESS";
export const DELETEWASTE_ERROR = "DELETEWASTE_ERROR";

export const DELETEUSER_BEGIN = "UPDATEUSER_BEGIN";
export const DELETEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const DELETEUSER_ERROR = "UPDATEUSER_ERROR";
